name: firebase_core_module
description: "help apply firebase_core to project"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/firebase_core_module

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_core: #@add
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/firebase_core_module/
  uses-material-design: true